  - name: Read prompt from file
    id: read_prompt
    run: echo "PROMPT=$(cat prompt.txt)" >> $GITHUB_ENV

  - name: Call Gemini API
    id: call_api
    run: |
      PROMPT_TEXT=$(echo "${{ env.PROMPT }}" | sed 's/"/\\"/g')
      
      RESPONSE_CONTENT=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key=${{ secrets.API_KEY }}" \
        -H 'Content-Type: application/json' \
        -d "{
          \"contents\": [
            {
              \"parts\": [
                {
                  \"text\": \"$PROMPT_TEXT\"
                }
              ]
            }
          ]
        }" | jq -r '.candidates[0].content.parts[0].text')
        
      echo "response_text<<EOF" >> $GITHUB_ENV
      echo "$RESPONSE_CONTENT" >> $GITHUB_ENV
      echo "EOF" >> $GITHUB_ENV

  - name: Write response to file
    run: |
      echo "${{ env.response_text }}" > response.txt
      git config --global user.email "github-actions[bot]@users.noreply.github.com"
      git config --global user.name "github-actions[bot]"
      git add response.txt
      git commit -m "Updated response.txt"
      git push